### PR TITLE
Fix DispatchAudit Serialization Problems

### LINKED ISSUE #885: Enabling queue causes Unable to JSON encode payload. Error (5)
After updating to the latest version it seems that the queue is automatically enabled. 

This caused all my auditable models to stop saving and return this error:

`Unable to JSON encode payload. Error (5): Malformed UTF-8 characters, possibly incorrectly encoded {"userId":1,"exception":"[object] (Illuminate\\Queue\\InvalidPayloadException(code: 0): Unable to JSON encode payload. Error (5): Malformed UTF-8 characters, possibly incorrectly encoded at /app/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:109)`

Publishing the config and setting the queue to false solves the issue but it's not clear why this is happening.

laravel/framework v10.38.1
owen-it/laravel-auditing v13.6.3

Thanks Dan

### LINKED ISSUE #890: The events (DispatchAudit) are missing the SerializesModels trait
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10.38.1
| Package version   | 13.6.3
| PHP version       | 8.2.13

#### Actual Behaviour

The constructor of the model is not being called for a queued audit event. As I'm initializing a protected property in the constructor. So, as the contractor is not called that property is never initialized. 

This is due to, the `OwenIt\Auditing\Events\DispatchAudit` listener missing the `Illuminate\Queue\SerializesModels` trait which results in a large payload for the queue. Also without this, the models are just hydrated/unserialized without calling the construct. Which also makes an issue for me. As I'm initializing a protected property in the constructor. So, as the contractor is not called that property is never initialized.

#### Expected Behaviour
The model should be hydrated from the database instead of just unserializing from the job payload.

#### Steps to Reproduce
Create an auditable model with a constructor to perform some action. .e.g. to initialize a protected model property. 
Then perform some action on model create/update. 
You'll notice that the constructor is not called.

#### Possible Solutions
Please use the `Illuminate\Queue\SerializesModels` trait for both events or at least for `OwenIt\Auditing\Events\DispatchAudit`.

### LINKED ISSUE #891: Serialization of 'Closure' is not allowed
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10.38.1
| Package version   | 13.6.3
| PHP version       | 8.2.14

#### Actual Behaviour

We audit a model `App\Models\Project`. The model has a slug column `projects.slug` which is managed by the [spatie/laravel-sluggable](https://github.com/spatie/laravel-sluggable) package. Since the latest update from 13.5.1 to 13.6.3 creating a new project (`Project::create([...])`) will throw an error, see below. The user gets a 500 error message. The project is created. There is no audit entry.

We figured out that the error occurs as soon as we define an `extraScope` for the slug feature, see [scopes](https://github.com/spatie/laravel-sluggable?tab=readme-ov-file#using-scopes).

Of course we can set the config `audit.queue.enable` to `false` and then the error is gone, too.

```bash
[2023-12-22 17:32:35] local.ERROR: Serialization of 'Closure' is not allowed {"userId":1,"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:159)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(159): serialize()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(128): Illuminate\\Queue\\Queue->createObjectPayload()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(106): Illuminate\\Queue\\Queue->createPayloadArray()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(38): Illuminate\\Queue\\Queue->createPayload()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(147): Illuminate\\Queue\\SyncQueue->push()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(72): Illuminate\\Queue\\SyncQueue->later()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(634): Illuminate\\Queue\\Queue->laterOn()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(552): Illuminate\\Events\\Dispatcher->queueHandler()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#11 /var/www/html/vendor/owen-it/laravel-auditing/src/AuditableObserver.php(118): Illuminate\\Events\\Dispatcher->dispatch()
#12 /var/www/html/vendor/owen-it/laravel-auditing/src/AuditableObserver.php(41): OwenIt\\Auditing\\AuditableObserver->dispatchAudit()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): OwenIt\\Auditing\\AuditableObserver->created()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(188): Illuminate\\Events\\Dispatcher->dispatch()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1319): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1137): Illuminate\\Database\\Eloquent\\Model->performInsert()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(342): Illuminate\\Database\\Eloquent\\Model->save()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany->Illuminate\\Database\\Eloquent\\Relations\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(339): tap()
#22 /var/www/html/app/Actions/CreateProject.php(21): Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany->create()
#23 /var/www/html/app/Http/Controllers/Web/ProjectController.php(66): App\\Actions\\CreateProject->__invoke()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Web\\ProjectController->store()
```

#### Expected Behaviour

We can create a project without error message. An audit entry is created and the slug is generated, respecting any extra scopes.

#### Steps to Reproduce

- Create a fresh laravel project
- Install `composer require owen-it/laravel-auditing`
- publish config `php artisan vendor:publish --provider "OwenIt\Auditing\AuditingServiceProvider" --tag="config"`
- publish migration `php artisan vendor:publish --provider "OwenIt\Auditing\AuditingServiceProvider" --tag="migrations"`
- Install `composer require spatie/laravel-sluggable`
- Define model `Project` with migration, two columns `projects.name` and `projects.slug`
- Migrate
- Make the model auditable
- Make the model sluggable
- Define an `extraScope`
- Create a model

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use OwenIt\Auditing\Auditable as AuditingAuditable;
use OwenIt\Auditing\Contracts\Auditable;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Project extends Model implements Auditable
{
    use HasFactory;
    use AuditingAuditable;
    use HasSlug;

    protected $fillable = [
        'name',
    ];

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug')
            ->doNotGenerateSlugsOnUpdate()
            ->extraScope(fn ($builder) => $builder->whereNotNull('created_at')); // just for demonstration
    }
}
```

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('projects', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('projects');
    }
};

```

image

### LINKED ISSUE #892: ErrorException: Undefined array key "table" in /vendor/laravel/framework/src/Illuminate/Queue/Connectors/DatabaseConnector.php:38
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no|
| Framework         | Laravel|Lumen
| Framework version | 10.39.0
| Package version   | 13.6.1
| PHP version       | 8.2.0

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Connectors/DatabaseConnector.php(38): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(163): Illuminate\\Queue\\Connectors\\DatabaseConnector->connect()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(138): Illuminate\\Queue\\QueueManager->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(620): Illuminate\\Queue\\QueueManager->connection()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(552): Illuminate\\Events\\Dispatcher->queueHandler()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#9 /var/www/html/vendor/owen-it/laravel-auditing/src/AuditableObserver.php(118): Illuminate\\Events\\Dispatcher->dispatch()
#10 /var/www/html/vendor/owen-it/laravel-auditing/src/AuditableObserver.php(41): OwenIt\\Auditing\\AuditableObserver->dispatchAudit()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): OwenIt\\Auditing\\AuditableObserver->created()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(188): Illuminate\\Events\\Dispatcher->dispatch()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1319): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1137): Illuminate\\Database\\Eloquent\\Model->performInsert()
#17 /var/www/html/app/Http/Controllers/SacClientController.php(693): Illuminate\\Database\\Eloquent\\Model->save()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\SacClientController->sendMsgProtocol()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#24 /var/www/html/app/Http/Middleware/sacClientHasLogin.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\sacClientHasLogin->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 /var/www/html/app/Http/Middleware/GuardSwitcher.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\GuardSwitcher->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#43 /var/www/html/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#45 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#47 /var/www/html/app/Http/Middleware/RequestSanitizer.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\RequestSanitizer->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#71 /var/www/html/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()
#72 /var/www/html/server.php(21): require_once('...')
#73 {main}
"} 

#### Steps to Reproduce

    'resolver' => [
        'user'       => App\Audit\Resolver\UserResolver::class,
        'ip_address' => OwenIt\Auditing\Resolvers\IpAddressResolver::class,
        'user_agent' => OwenIt\Auditing\Resolvers\UserAgentResolver::class,
        'url'        => OwenIt\Auditing\Resolvers\UrlResolver::class,
    ],
#### my code
```<?php
namespace App\Audit\Resolver;

use App\Model\Users;
use OwenIt\Auditing\Contracts\UserResolver as ResolverContract;

class UserResolver implements ResolverContract{

    /**
     * Resolve the User.
     *
     * @return mixed|null
     */
    public static function resolve(){
        return Users::where('r_code', session('r_code'))->first();
    }
}

<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable;
use Illuminate\Support\Facades\DB;

class SacMsgProtocol extends Model implements Auditable
{
	use AuditableTrait;
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'sac_msg_protocol';
 /.../
}

This error happens when I save a new SacMsgProtocol
Example:
 $message = new SacMsgProtocol;
            $message->message = $request->msg;
            $message->sac_protocol_id = $request->id;
$message->save();

### LINKED ISSUE #895: Binary attribute casting no longer works in new versions (works flawlessly with v13.5.1)
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10.28.0
| Package version   | 13.6.3
| PHP version       | 8.1.0

#### Actual Behaviour

Binary uuid started creating error "Json malformed (Errno: 5)" even with use of a custom attribute modifier to cast from bytes to string and string to bytes. It worked fine for months till I updated from v13.5.1 to v13.6.3. I downgraded to  v13.5.1 and it started working back fine as expected. 

#### Expected Behaviour

After investigation, it looks like my custom BinaryUuid::class is no longer called and the object to be casted into json still contains binary information. With v13.5.1 I can confirm that it my attribute modifiers is called to cast binary data into string

#### Steps to Reproduce

Here is the class I used in my models that have binary uuid (Dyryndra/Laravel-efficient-uuid):

`class BinaryUuid implements AttributeEncoder
{

    public static function encode($value)
    {
        if (blank($value)) {
            return null;
        }
        return Uuid::fromBytes($value)->toString();
    }

    public static function decode($value)
    {
        if (blank($value)) {
            return null;
        }
        return Uuid::fromString(strtolower($value))->getBytes();
    }

}`

And then I do this in Models:

`protected $attributeModifiers = [
        "id" => BinaryUuid::class,
        "withhold_of" => BinaryUuid::class,
        "slavery" => BinaryUuid::class,
        "pin" => RightRedactor::class
    ];
`

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

### PR DESCRIPTION
**Pull request by erikn69**
~Testing `SerializesModels`~ `SerializesModels` was unnecessary
Closes #892
Closes #891
Closes #890
Closes #895
Closes #885
I think this complicates things quite a bit.

### CODE REVIEW

File: src/Events/DispatchAudit.php [hunk 1]
```diff
@@ -22,4 +23,88 @@ public function __construct(Auditable $model)
...
+     * Prepare the instance values for serialization.
+     *
+     * @return array
+     */
+    public function __serialize()
+    {
+        $values = [
+            'class' => get_class($this->model),
+            'model_data' => [
+                'exists' => true,
```
Comment (mjawad096) [inline src/Events/DispatchAudit.php:37]: You should also save the model id, so that it can be retrieved by id in unserialization

File: src/Events/DispatchAudit.php [hunk 2]
```diff
@@ -22,4 +23,88 @@ public function __construct(Auditable $model)
...
+
+    /**
+     * Restore the model after serialization.
+     *
+     * @param  array  $values
+     * @return array
+     */
+    public function __unserialize(array $values)
+    {
+        $this->model = new $values['class'];
```
Comment (mjawad096) [inline src/Events/DispatchAudit.php:75]: It should be changed something like `$this->model = $values['class']::findOrFail($values['id']);`

**Review by mjawad096 — CHANGES_REQUESTED** [review]

**Comment by cangelis** [comment]
I think we should also have a test failing before the patch to ensure it really is fixed and never happening again.

File: src/Events/DispatchAudit.php (hunk 1 above)
Comment (mjawad096) [reply src/Events/DispatchAudit.php:37]: I see

**Review by mjawad096 — APPROVED** [review]

File: src/Events/DispatchAudit.php (hunk 1 above)
Comment (erikn69) [reply src/Events/DispatchAudit.php:37]: Also Id comes with attributes, original properties

File: src/Events/DispatchAudit.php (hunk 2 above)
Comment (erikn69) [reply src/Events/DispatchAudit.php:75]: > the model shouldn't be retrieved from the database at all as the old and the new values will get lost in case the model gets updated again before the job is dispatched

**Comment by erikn69** [comment]
@cangelis test added, but i don't use sanctum, was the `__sleep()` problem fixed?

**Review by MortenDHansen — APPROVED** [review]

**Review by parallels999 — APPROVED** [review]
